# French translations for python-watcher.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the python-watcher
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
msgid ""
msgstr ""
"Project-Id-Version: python-watcher 0.21.1.dev32\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-01-19 17:54+0100\n"
"PO-Revision-Date: 2015-12-11 15:42+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: fr\n"
"Language-Team: fr <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.1.1\n"

#: watcher/api/controllers/v1/action_plan.py:102
#, python-format
msgid "Invalid state: %(state)s"
msgstr "État invalide : %(state)s"

#: watcher/api/controllers/v1/action_plan.py:418
#, python-format
msgid "State transition not allowed: (%(initial_state)s -> %(new_state)s)"
msgstr "Transition d'état non autorisée : (%(initial_state)s -> %(new_state)s)"

#: watcher/api/controllers/v1/types.py:148
#, python-format
msgid "%s is not JSON serializable"
msgstr ""

#: watcher/api/controllers/v1/types.py:184
#, python-format
msgid "Wrong type. Expected '%(type)s', got '%(value)s'"
msgstr ""

#: watcher/api/controllers/v1/types.py:223
#, python-format
msgid "'%s' is an internal attribute and can not be updated"
msgstr ""

#: watcher/api/controllers/v1/types.py:227
#, python-format
msgid "'%s' is a mandatory attribute and can not be removed"
msgstr "'%s' est un attribut obligatoire et ne peut pas être enlevé"

#: watcher/api/controllers/v1/types.py:232
msgid "'add' and 'replace' operations needs value"
msgstr "Les opérations 'add' et 'replace' recquièrent une valeur"

#: watcher/api/controllers/v1/utils.py:36
msgid "Limit must be positive"
msgstr "Limit doit être positif"

#: watcher/api/controllers/v1/utils.py:47
#, python-format
msgid "Invalid sort direction: %s. Acceptable values are 'asc' or 'desc'"
msgstr ""

#: watcher/api/controllers/v1/utils.py:57
#, python-format
msgid "Adding a new attribute (%s) to the root of  the resource is not allowed"
msgstr ""

#: watcher/api/middleware/auth_token.py:45
msgid "Cannot compile public API routes"
msgstr ""

#: watcher/api/middleware/parsable_error.py:52
#, python-format
msgid "ErrorDocumentMiddleware received an invalid status %s"
msgstr ""

#: watcher/api/middleware/parsable_error.py:80
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: watcher/applier/actions/change_nova_service_state.py:58
msgid "The target state is not defined"
msgstr ""

#: watcher/applier/workflow_engine/default.py:69
#, python-format
msgid "The WorkFlow Engine has failed to execute the action %s"
msgstr "Le moteur de workflow a echoué lors de l'éxécution de l'action %s"

#: watcher/applier/workflow_engine/default.py:77
#, python-format
msgid "Revert action %s"
msgstr "Annulation de l'action %s"

#: watcher/applier/workflow_engine/default.py:83
msgid "Oops! We need disaster recover plan"
msgstr "Oops! Nous avons besoin d'un plan de reprise d'activité"

#: watcher/cmd/api.py:46 watcher/cmd/applier.py:39
#: watcher/cmd/decisionengine.py:40
#, python-format
msgid "Starting server in PID %s"
msgstr "Démarre le serveur avec pour PID %s"

#: watcher/cmd/api.py:51
#, python-format
msgid "serving on 0.0.0.0:%(port)s, view at http://127.0.0.1:%(port)s"
msgstr "Sert sur 0.0.0.0:%(port)s, accessible à http://127.0.0.1:%(port)s"

#: watcher/cmd/api.py:55
#, python-format
msgid "serving on http://%(host)s:%(port)s"
msgstr "Sert sur http://%(host)s:%(port)s"

#: watcher/common/exception.py:56
msgid "An unknown exception occurred"
msgstr ""

#: watcher/common/exception.py:77
msgid "Exception in string format operation"
msgstr ""

#: watcher/common/exception.py:107
msgid "Not authorized"
msgstr ""

#: watcher/common/exception.py:112
msgid "Operation not permitted"
msgstr ""

#: watcher/common/exception.py:116
msgid "Unacceptable parameters"
msgstr ""

#: watcher/common/exception.py:121
#, python-format
msgid "The %(name)s %(id)s could not be found"
msgstr ""

#: watcher/common/exception.py:125
#, fuzzy
msgid "Conflict"
msgstr "Conflit."

#: watcher/common/exception.py:130
#, python-format
msgid "The %(name)s resource %(id)s could not be found"
msgstr ""

#: watcher/common/exception.py:135
#, python-format
msgid "Expected an uuid or int but received %(identity)s"
msgstr ""

#: watcher/common/exception.py:139
#, python-format
msgid "Goal %(goal)s is not defined in Watcher configuration file"
msgstr ""

#: watcher/common/exception.py:145
#, python-format
msgid "%(err)s"
msgstr ""

#: watcher/common/exception.py:149
#, python-format
msgid "Expected a uuid but received %(uuid)s"
msgstr ""

#: watcher/common/exception.py:153
#, python-format
msgid "Expected a logical name but received %(name)s"
msgstr ""

#: watcher/common/exception.py:157
#, python-format
msgid "Expected a logical name or uuid but received %(name)s"
msgstr ""

#: watcher/common/exception.py:161
#, python-format
msgid "AuditTemplate %(audit_template)s could not be found"
msgstr ""

#: watcher/common/exception.py:165
#, python-format
msgid "An audit_template with UUID %(uuid)s or name %(name)s already exists"
msgstr ""

#: watcher/common/exception.py:170
#, python-format
msgid "AuditTemplate %(audit_template)s is referenced by one or multiple audit"
msgstr ""

#: watcher/common/exception.py:175
#, python-format
msgid "Audit %(audit)s could not be found"
msgstr ""

#: watcher/common/exception.py:179
#, python-format
msgid "An audit with UUID %(uuid)s already exists"
msgstr ""

#: watcher/common/exception.py:183
#, python-format
msgid "Audit %(audit)s is referenced by one or multiple action plans"
msgstr ""

#: watcher/common/exception.py:188
msgid "ActionPlan %(action plan)s could not be found"
msgstr ""

#: watcher/common/exception.py:192
#, python-format
msgid "An action plan with UUID %(uuid)s already exists"
msgstr ""

#: watcher/common/exception.py:196
#, python-format
msgid "Action Plan %(action_plan)s is referenced by one or multiple actions"
msgstr ""

#: watcher/common/exception.py:201
#, python-format
msgid "Action %(action)s could not be found"
msgstr ""

#: watcher/common/exception.py:205
#, python-format
msgid "An action with UUID %(uuid)s already exists"
msgstr ""

#: watcher/common/exception.py:209
#, python-format
msgid "Action plan %(action_plan)s is referenced by one or multiple goals"
msgstr ""

#: watcher/common/exception.py:214
msgid "Filtering actions on both audit and action-plan is prohibited"
msgstr ""

#: watcher/common/exception.py:223
#, python-format
msgid "Couldn't apply patch '%(patch)s'. Reason: %(reason)s"
msgstr ""

#: watcher/common/exception.py:233
msgid "Description must be an instance of str"
msgstr ""

#: watcher/common/exception.py:243
msgid "An exception occurred without a description"
msgstr ""

#: watcher/common/exception.py:251
msgid "Description cannot be empty"
msgstr ""

#: watcher/common/exception.py:260
msgid "No such metric"
msgstr ""

#: watcher/common/exception.py:269
msgid "No rows were returned"
msgstr ""

#: watcher/common/exception.py:277
msgid "'Keystone API endpoint is missing''"
msgstr ""

#: watcher/common/exception.py:281
msgid "The list of hypervisor(s) in the cluster is empty"
msgstr ""

#: watcher/common/exception.py:285
msgid "The metrics resource collector is not defined"
msgstr ""

#: watcher/common/exception.py:289
msgid "the cluster state is not defined"
msgstr ""

#: watcher/common/exception.py:295
#, python-format
msgid "The instance '%(name)s' is not found"
msgstr "L'instance '%(name)s' n'a pas été trouvée"

#: watcher/common/exception.py:299
msgid "The hypervisor is not found"
msgstr ""

#: watcher/common/exception.py:303
#, fuzzy, python-format
msgid "Error loading plugin '%(name)s'"
msgstr "Erreur lors du chargement du module '%(name)s'"

#: watcher/common/keystone.py:59
msgid "No Keystone service catalog loaded"
msgstr ""

#: watcher/common/service.py:83
#, python-format
msgid "Created RPC server for service %(service)s on host %(host)s."
msgstr ""

#: watcher/common/service.py:92
#, python-format
msgid "Service error occurred when stopping the RPC server. Error: %s"
msgstr ""

#: watcher/common/service.py:97
#, python-format
msgid "Service error occurred when cleaning up the RPC manager. Error: %s"
msgstr ""

#: watcher/common/service.py:101
#, python-format
msgid "Stopped RPC server for service %(service)s on host %(host)s."
msgstr ""

#: watcher/common/service.py:106
#, python-format
msgid ""
"Got signal SIGUSR1. Not deregistering on next shutdown of service "
"%(service)s on host %(host)s."
msgstr ""

#: watcher/common/utils.py:53
#, python-format
msgid ""
"Failed to remove trailing character. Returning original object. Supplied "
"object is not a string: %s,"
msgstr ""

#: watcher/common/messaging/messaging_handler.py:98
msgid "No endpoint defined; can only publish events"
msgstr ""

#: watcher/common/messaging/messaging_handler.py:101
msgid "Messaging configuration error"
msgstr ""

#: watcher/db/sqlalchemy/api.py:256
msgid ""
"Multiple audit templates exist with the same name. Please use the audit "
"template uuid instead"
msgstr ""

#: watcher/db/sqlalchemy/api.py:277
msgid "Cannot overwrite UUID for an existing AuditTemplate."
msgstr ""

#: watcher/db/sqlalchemy/api.py:386 watcher/db/sqlalchemy/api.py:586
msgid "Cannot overwrite UUID for an existing Audit."
msgstr ""

#: watcher/db/sqlalchemy/api.py:477
msgid "Cannot overwrite UUID for an existing Action."
msgstr ""

#: watcher/db/sqlalchemy/migration.py:73
msgid ""
"Watcher database schema is already under version control; use upgrade() "
"instead"
msgstr ""

#: watcher/decision_engine/model/model_root.py:37
#: watcher/decision_engine/model/model_root.py:42
msgid "'obj' argument type is not valid"
msgstr ""

#: watcher/decision_engine/planner/default.py:75
msgid "The action plan is empty"
msgstr ""

#: watcher/decision_engine/strategy/selection/default.py:59
#, python-format
msgid "Incorrect mapping: could not find associated strategy for '%s'"
msgstr ""

#: watcher/decision_engine/strategy/strategies/basic_consolidation.py:267
#: watcher/decision_engine/strategy/strategies/basic_consolidation.py:314
#, python-format
msgid "No values returned by %(resource_id)s for %(metric_name)s"
msgstr ""

#: watcher/decision_engine/strategy/strategies/basic_consolidation.py:349
msgid "Initializing Sercon Consolidation"
msgstr ""

#: watcher/decision_engine/strategy/strategies/basic_consolidation.py:406
msgid "The workloads of the compute nodes of the cluster is zero"
msgstr ""

#: watcher/decision_engine/strategy/strategies/outlet_temp_control.py:125
#, python-format
msgid "%s: no outlet temp data"
msgstr ""

#: watcher/decision_engine/strategy/strategies/outlet_temp_control.py:149
#, python-format
msgid "VM not active, skipped: %s"
msgstr ""

#: watcher/decision_engine/strategy/strategies/outlet_temp_control.py:206
msgid "No hosts under outlet temp threshold found"
msgstr ""

#: watcher/decision_engine/strategy/strategies/outlet_temp_control.py:229
msgid "No proper target host could be found"
msgstr ""

#: watcher/objects/base.py:70
#, python-format
msgid "Error setting %(attr)s"
msgstr ""

#: watcher/objects/base.py:108
msgid "Invalid version string"
msgstr ""

#: watcher/objects/base.py:172
#, python-format
msgid "Unable to instantiate unregistered object type %(objtype)s"
msgstr ""

#: watcher/objects/base.py:299
#, python-format
msgid "Cannot load '%(attrname)s' in the base class"
msgstr ""

#: watcher/objects/base.py:308
msgid "Cannot save anything in the base class"
msgstr ""

#: watcher/objects/base.py:340
#, python-format
msgid "%(objname)s object has no attribute '%(attrname)s'"
msgstr ""

#: watcher/objects/base.py:390
#, python-format
msgid "'%(objclass)s' object has no attribute '%(attrname)s'"
msgstr ""

#: watcher/objects/utils.py:40
msgid "A datetime.datetime is required here"
msgstr ""

#: watcher/objects/utils.py:105
#, python-format
msgid "An object of class %s is required here"
msgstr ""

#~ msgid "Cannot compile public API routes: %s"
#~ msgstr ""

#~ msgid "An exception occurred without a description."
#~ msgstr ""

#~ msgid "no rows were returned"
#~ msgstr ""

#~ msgid ""
#~ msgstr ""

#~ msgid "An unknown exception occurred."
#~ msgstr ""

#~ msgid "Not authorized."
#~ msgstr ""

#~ msgid "Operation not permitted."
#~ msgstr ""

#~ msgid "Unacceptable parameters."
#~ msgstr ""

#~ msgid "The %(name)s %(id)s could not be found."
#~ msgstr ""

#~ msgid "The %(name)s resource %(id)s could not be found."
#~ msgstr ""

#~ msgid "Expected an uuid or int but received %(identity)s."
#~ msgstr ""

#~ msgid "Goal %(goal)s is not defined in Watcher configuration file."
#~ msgstr ""

#~ msgid "Expected a uuid but received %(uuid)s."
#~ msgstr ""

#~ msgid "Expected a logical name but received %(name)s."
#~ msgstr ""

#~ msgid "Expected a logical name or uuid but received %(name)s."
#~ msgstr ""

#~ msgid "AuditTemplate %(audit_template)s could not be found."
#~ msgstr ""

#~ msgid "An audit_template with UUID %(uuid)s or name %(name)s already exists."
#~ msgstr ""

#~ msgid "Audit %(audit)s could not be found."
#~ msgstr ""

#~ msgid "An audit with UUID %(uuid)s already exists."
#~ msgstr ""

#~ msgid "Audit %(audit)s is referenced by one or multiple action plans."
#~ msgstr ""

#~ msgid "ActionPlan %(action plan)s could not be found."
#~ msgstr ""

#~ msgid "An action plan with UUID %(uuid)s already exists."
#~ msgstr ""

#~ msgid "Action Plan %(action_plan)s is referenced by one or multiple actions."
#~ msgstr ""

#~ msgid "Action %(action)s could not be found."
#~ msgstr ""

#~ msgid "An action with UUID %(uuid)s already exists."
#~ msgstr ""

#~ msgid "Action plan %(action_plan)s is referenced by one or multiple goals."
#~ msgstr ""

#~ msgid "Filtering actions on both audit and action-plan is prohibited."
#~ msgstr ""

#~ msgid "The list of hypervisor(s) in the cluster is empty.'"
#~ msgstr ""

#~ msgid "The metrics resource collector is not defined.'"
#~ msgstr ""

#~ msgid "The VM could not be found."
#~ msgstr ""

#~ msgid "The hypervisor could not be found."
#~ msgstr ""

#~ msgid "The Meta-Action could not be found."
#~ msgstr ""

#~ msgid "'hypervisor' argument type is not valid"
#~ msgstr ""

#~ msgid "'vm' argument type is not valid"
#~ msgstr ""

#~ msgid "The Meta-Action could not be found"
#~ msgstr ""

#~ msgid "The VM could not be found"
#~ msgstr ""

#~ msgid "The hypervisor could not be found"
#~ msgstr ""

#~ msgid "Trigger a rollback"
#~ msgstr ""

#~ msgid "The WorkFlow Engine has failedto execute the action %s"
#~ msgstr ""

